name: Create Embeddings
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: textchunks
    required: false
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to write to.
    defaultValue: trashcan
    required: false
  - name: groupname
    inputType: FreeText
    description: ''
    defaultValue: vectorizer-v1a
    required: false
  - name: textfield
    inputType: FreeText
    description: ''
    defaultValue: chunks
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
