name: Create Sections to Summarize
language: Python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: v2-transcriptions
    required: false
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to write to.
    defaultValue: segments-to-summarize
    required: false
  - name: groupname
    inputType: FreeText
    description: ''
    defaultValue: chunkster-v1
    required: false
  - name: deltaminutes
    inputType: FreeText
    description: ''
    defaultValue: 1
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
